---
title: "Plotly Hello World"
author: "Tiago Carvalho"
date: "January 26, 2017"
output:
  ioslides_presentation: default
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(plotly)

```

## Introduction

This presentation is an Hello World using Plotly. It is also part of the Assignments of the Developing Data Products Coursera course.
The dataset used is on the bundled ones preloaded in R, and one that was used in class - mtcars.
The inspiration for the chart itself came from the examples in the plotly website: https://plot.ly/r/#3d-charts

## R code used

```{r cars, echo = TRUE}
mtcars$am[which(mtcars$am == 0)] <- 'Automatic'
mtcars$am[which(mtcars$am == 1)] <- 'Manual'
mtcars$am <- as.factor(mtcars$am)

p <- plot_ly(mtcars, x = ~wt, y = ~hp, z = ~qsec, color = ~am, 
             colors = c('#BF382A', '#0C4B8E')) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'Weight'),
                     yaxis = list(title = 'Gross horsepower'),
                     zaxis = list(title = '1/4 mile time')))
```

## Resulting plot

```{r pressure, echo=TRUE, warning=FALSE}
p

```

